services:
  - type: web
    name: move2earn-backend
    env: docker
    region: oregon
    plan: free
    startCommand: "gunicorn -w 4 -b 0.0.0.0:$PORT wsgi:app"
    envVars:
      - key: FLASK_SECRET_KEY
        sync: false
      - key: MONGO_URI
        sync: false
      - key: STRAVA_CLIENT_ID
        sync: false
      - key: STRAVA_CLIENT_SECRET
        sync: false
      - key: STRAVA_REFRESH_TOKEN
        sync: false
